In [2]:
import pandas as pd

# Load CSV file
df = pd.read_csv("master_table.csv")

# Display the first few rows to check structure
df.head()

,PN,OD,ID,Height,AWG,Min Diameter,Nominal Diameter,Max Diameter,Effective Diameter,Turns,AL,Inductance,Fill Factor
0,T80-26,0.795,0.495,0.25,10.0,0.1026,0.1037,0.1047,0.105774,11,46.0,5.566,0.482769
1,T80-26,0.795,0.495,0.25,11.0,0.0915,0.0925,0.0936,0.094350,13,46.0,7.774,0.453959
2,T80-26,0.795,0.495,0.25,12.0,0.0816,0.0825,0.0835,0.084150,15,46.0,10.350,0.416667
3,T80-26,0.795,0.495,0.25,13.0,0.0729,0.0737,0.0746,0.075174,17,46.0,13.294,0.376854
4,T80-26,0.795,0.495,0.25,14.0,0.0651,0.0659,0.0666,0.067218,19,46.0,16.606,0.336755

In [7]:
fdf = df[['PN', 'OD', 'ID', 'Height', 'AWG', 'Turns', 'AL', 'Inductance', 'Fill Factor']]
fdf = fdf[(fdf['PN'] == "T184-26") & (fdf['AWG'] <= 14.0) & (fdf['AWG'] >= 11.0)]
fdf

         PN    OD    ID  Height   AWG  Turns     AL  Inductance  Fill Factor
28  T184-26  1.84  0.95    0.71  11.0     28  169.0     132.496     0.265457
29  T184-26  1.84  0.95    0.71  12.0     32  169.0     173.056     0.241330
30  T184-26  1.84  0.95    0.71  13.0     36  169.0     219.024     0.216666
31  T184-26  1.84  0.95    0.71  14.0     41  169.0     284.089     0.197291